### ISSUE TITLE
Fallback error screen for frontend crashes

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#160]
During development of the web VCC, we've seen many bugs that can cause the frontend to fail.
For example, invalid settings.json files or lack of an internet connection can cause the VCC to render a blank, black screen.
The logs folder usually doesn't yield useful errors in those circumstances.

We should add a default screen that shows up when the frontend fails to load, perhaps showing additional frontend errors or troubleshooting steps.

**Comment by Faxmashine** [comment]
I've fixed this issue, for the most part. Instead of crashing or showing a black screen, the user gets an error informing them about their malformed settings file. The file is usually empty.

We haven't received any reports from users about blank/blank screens, though some users have reported the app closing immediately after opening it.

I don't think either of those issues would be solved by adding a fallback screen. We should reopen this issue if it comes up again.
