### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by StinkyDemon666** [vrchat-community/creator-companion#374]
### Describe the bug

once i auto fix everything the validation menu disappears and becomes un uploadable 
![Screenshot 2023-10-23 203452](https://github.com/vrchat-community/creator-companion/assets/148837546/da5079f0-dff9-47e6-bb09-161cb156987a)

### To Reproduce

open sdk and upload a model
autofix everything
dissapears

### Expected behavior

upload to vrchat button

### Screenshots

![Screenshot 2023-10-23 203452](https://github.com/vrchat-community/creator-companion/assets/148837546/50436945-2641-4137-adfd-dc75016c3de3)
![image](https://github.com/vrchat-community/creator-companion/assets/148837546/5f59ae25-d365-428d-ba57-a390fc7013b0)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.1

### OS

Windows 10

**Comment by orels1** [comment]
This is not a Creator-Companion issue, but since we're here already

Based on that tiny sliver of a console log on your last screenshot - the issue comes from the fact that your avatar doesn't have an animator component on it.

The latest VRC SDK (3.4.1) has special handling for that specific error which shows up in the Validations list instead of just going blank and spamming the console

You need to add add an Animator component to your avatar root (Where the VRC Avatar Descriptor is)
