### ISSUE TITLE
Problem with installing Creator Companion after my HDD died.

### ISSUE THREAD

**Issue by Cassiya** [vrchat-community/creator-companion#421]
![image_2024-01-13_214229169](https://github.com/vrchat-community/creator-companion/assets/156546162/352d0a6a-b0a9-47de-a702-939bd988948f)
So my HDD died like a week ago, I had Creator Companion installed there, however when I try to install it again, it gives me the error, shown in the picture above since I can not change the location of where it is going to be installed, I can not really do anything about it and I have been told to remove the old creator companion from the registry since I can not uninstall it, nor does it give me the option to remove it, shown in the following picture (System can not locate said drive): 
![image](https://github.com/vrchat-community/creator-companion/assets/156546162/006d1f34-f58a-4bde-8e10-6f138e939460)

I can not find it in the registry, I do not know the key, nor the location and I do not know what to do now, removing the old dead drive did not work, the only way I could fix it possibly is by reinstalling windows but I did that recently, I would rather avoid it until I am completely out of options. Any ideas?

**Comment by orels1** [comment]
Hey!
It seems like the issue is with the registry key being leftover. You should be able to fix it by doing the following:
- Open the registry editor by searching for "Registry Editor" in your start window
- In there navigate to HKEY_CURRENT_USER -> Software
- Delete the VCC folder

![image](https://github.com/vrchat-community/creator-companion/assets/3798928/63549e6b-1286-42bb-a865-b9420a86af4d)

This should allow you to install the VCC again
Hope that helps!
