### ISSUE TITLE
[BUG] Resolve needed dialog is shown for already resolved project

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#460]
### Describe the bug

Resolve needed dialog is shown for already resolved project

### To Reproduce

1. Create new vpm project
2. replace vpm-manifest.json with [vpm-manifest.json](https://github.com/vrchat-community/creator-companion/files/14961152/vpm-manifest.json)
3. open the project in vcc and resolve it
4. close the VCC and re-open the VCC

### Expected behavior

no resolve needed dialog is opened

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.0 beta.2

### OS

Windows 11

### Additional context

Related #450

**Comment by orels1** [comment]
Thanks for the report and the manifest file!

I was able to find the source of the issue - the `com.anatawa12.continuous-avatar-uploader` defines a dependency range of `>=3.3.0-beta.1 <3.5.0` while the manifest also shows an explicitly installed `3.5.2` so the resolve logic doesnt see a satisfying version of the package and fails.

This specific check was added because we found some project manifests that do not have all the dependencies listed in the `locked` section and just relied on transient dependencies being installed no matter what (a legacy piece of VPM's many fallback code paths), which shouldn't really be happening in a case like this.

We will adjust the logic to simply check for the exact locked versions on disk instead, thank you!

PS. I would appreciate if you could attach the listing URLs when submitting a full manifest in the future, some of these were a little tough to track down!

**Comment by orels1** [comment]
This will be available in final 2.3.0 release

**Comment by orels1** [comment]
This has been released to live with version 2.3.0: https://vrcpm.vrchat.cloud/vcc/Builds/2.3.0/VRChat_CreatorCompanion_Setup_2.3.0.exe
