### ISSUE TITLE
[BUG] Update 2.4.0 Broke My VCC

### ISSUE THREAD

**Issue by Merishy** [vrchat-community/creator-companion#552]
### Describe the bug

Hello, after installing the new update I encounter this issue : the VCC comes in a white screen and opens an alert window "Microsoft Edge can't read and write to its data directory". 

I tried : 
- reinstalling the updated VCC
- repair Microsoft Edge
- enabling everyone to open the VCC app
- launching my PC once more 

The only solution is to go back to the last update so I came back to the version 2.3.4 and it works perfectly fine. I don't know what went wrong with the update.

### To Reproduce

1. Go to VCC.
2. Click on Update.
3. Update to 2.4.0.
4. Open it.
5. Windows alert "Microsoft Edge can't read and write to its data directory" and won't open the VCC.

### Expected behavior

I thought the update would go smoothly like the others but it didn't. I'm stuck in 2.3.4 hopefully it won't bother my avatars ?

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.4.0

### OS

Windows 11

**Comment by orels1** [comment]
Hey!
Not updating will not break any of your projects, so you don't need to worry about it.
We've seen this error before, but none of the changes we made should affect that.

This error generally appears when you have another application running that uses the same framework as the Creator Companion, which creates a conflict. So the fact that just going back to older version fixes it - is concerning. A clean restart should've at least cleared the older version of the VCC.

We're working on a way that should mitigate this issue, so if 2.3.4 works fine for you - you might want to just stick around with that for some time.

**Comment by naqtn** [comment]
@orels1 Some Japanese users are having this issue. They seem to use non-ASCII characters in their Windows's user name.

I could reproduce the issue.
1. create such account. (I use `いわゆる全角`)
2. login with the account
3. Start VCC

So this issue doesn't relate to the update process. Also, it is not the conflict issue you wrote:
> when you have another application running that uses the same framework as the Creator Companion, which creates a conflict.

The error dialog shows the actual data directory path, though the string is corrupt in the part of the user name of the APPDATA. I guess the issue relates to string handling.
![image](https://github.com/user-attachments/assets/bde97855-acaa-4d59-938c-01168ab4a7e8)

The files for the account are created successfully (maybe) in APPDATA, and I could not find any strange lines in the log `AppData\Local\VRChatCreatorCompanion\Logs\*-log.txt`.  The issue seems to happen only on the view side (I mean, not on the main process of VCC).

However, this issue is highly troublesome, especially for newcomers. They may easily (or helplessly) hit it. You (VRChat) should announce the problem and guide the workaround.

**Comment by orels1** [comment]
This is concerning. As this means this is probably connected to the Photino upgrade in 2.4.0 alongside the .net 6->8 bump

Are you aware of any workarounds? Or do you mean simply asking users to hold off on upgrading?

**Comment by naqtn** [comment]
I don't have any special ideas for the workaround.

Possible options are those (??):
- hold off on upgrading if you haven't yet
- downgrade to the previous (download the exe file and...)
- or change the folder name  (I'm not sure the proper way https://superuser.com/q/890812 )
- or create another account named without non-ASCII chars

**Comment by naqtn** [comment]
Just curious. Does this fix (merged to photino.NET v3.1.18) relate to the issue?
https://github.com/tryphotino/photino.NET/pull/214 (around `Photino_setWebView2RuntimePath_win32`)

In my environment, the folder `AppData\Local\Photino\EBWebView` doesn't exist for the account having the issue.  Compared to that, it exists for the account that does not have the problem (I usually use this).

**Comment by orels1** [comment]
That's a good catch, the folder exists for me and everything works as a result.

We are on version 3.1.17, I will bump to 3.1.18 and build a test version

**Comment by orels1** [comment]
We have updated Photino to version 3.2.3 which seems to address the issue.
This will go out in the 2.4.1 patch release soon

**Comment by orels1** [comment]
Hey @Merishy 
You should try the latest version 2.4.1 and see if it fixes your issue.
If not - we can open this issue back.
You can download the latest release of the VCC using the website or the release notes page: https://vcc.docs.vrchat.com/news/release-2.4.1

**Comment by Merishy** [comment]
> Hey @Merishy You should try the latest version 2.4.1 and see if it fixes your issue. If not - we can open this issue back. You can download the latest release of the VCC using the website or the release notes page: https://vcc.docs.vrchat.com/news/release-2.4.1

Hi there ! I tried it and it works so far, thanks for your hard work ! <3
