### ISSUE TITLE
[BUG] vpm-resolver will never show prerelease of packages

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#77]
**Describe the bug**
vpm-resolver does not show prerelease of packages and we cannot resolve to prereleases

**To Reproduce**
1. set showPrereleasePackages to true in settings.json
2. Add package with preleases in some project
3. Open vpm resolver
4. There's no prereleases in version list

**Expected behavior**
prereleases should be shown if `showPrereleasePackages` is true.

**Screenshots**

modular-avatar has 1.4.0-rc-3 but not listed

<img width="569" alt="image" src="https://user-images.githubusercontent.com/22656849/213351509-e025ac0e-35af-4fa9-b91a-9a9935b8bab0.png">

**Desktop (please complete the following information):**
 - OS: macOS 12 OR windows 11 22H2
 - Version: vpm-resolver 0.1.17

**Additional context**

**Comment by momo-the-monster** [comment]
Did some investigation on this with @calle242, reproduced the issue here. 
For future reference when working on this bug - the resolver calls `VPMPackageProvider.GetAllWithVersions()`, which internally calls into `VRCRepoList.GetAllWithVersions()`. This _should_ return all the packages, including prerelease versions, and then the front-end checks the Settings and filters out prerelease packages, or not. However, it only seems to return released versions at this point, despite the feature somehow working from the Unity and Web apps.

**Comment by momo-the-monster** [comment]
Aha! The Resolver class was trying to parse the version numbers using System.Version, which doesn't support prerelease packages. Introducing a proper `using` statement to use `VPMVersion` instead (which wraps `SemanticVersioning.Version`) seems to fix the issue! 
![image](https://user-images.githubusercontent.com/737888/216442927-f70c29d5-f885-4cf3-92f3-3f9187228974.png)

**Comment by d4rkc0d3r** [comment]
This seems to crash the vpm resolver if the only versions in one of the repos are prereleases.

**Comment by orels1** [comment]
This has been fixed as a part of 2.1.0.
The pre-release-only is still an issue but we'll address it separately
