### ISSUE TITLE
[BUG] [VCC-WEB]  VCC will only launch when directly starting the executable

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#84]
**Issue:**  
When I try to launch the VCC through my Taskbar, Shortcut or Windows Search it wont open. I always have to manually launch the executable in the VCC folder.  
When ever I do try to launch it that way I see a loading indicator on my cursor, but nothing happens.

**Expected Behavior:**  
The VCC should open no matter what way you try to launch it.

**Comment by momo-the-monster** [comment]
We had to change the executable name for the CreatorCompanionBeta from `CreatorCompanionBeta.exe` to `CreatorCompanion.exe` when we switched to the Web GUI, so any existing shortcuts for your Beta version might not work correctly.
Can you try making a new shortcut directly from the new .exe? That worked for me.
If you installed the CreatorCompanionBeta with typical settings (ie 'just for me' instead of 'for everyone') then you should be able to find the .exe in `%localappdata%\Programs\VRChat Creator Companion Beta`

**Comment by DrBlackRat** [comment]
Oh weird, now it seems to work fine. My main problem was that I couldn't even launch it via the Taskbar when just pining the program to it. After deleting the Shortcut out of the Startmenu folder and creating a new one it worked. I thought I deleted it originally when installing closed beta 2.
Anyway, problem seems fixed now.

**Comment by momo-the-monster** [comment]
Hm, I can verify that if I launch the VCC and pin the running program to the taskbar, then it will fail to relaunch. I'm guessing it's the same problem as #54.
